'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import styles from '../oraculum.module.css';
type Check={id:string;passed:boolean;actual:unknown;expected:unknown};
type Report={version:string;releaseId:string;passed:boolean;totalChecks:number;passedChecks:number;failedChecks:number;protocols:Record<string,string>;checks:Check[]};
export function Rc1QaClient(){
 const[report,setReport]=useState<Report|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 async function run(){setBusy(true);setError(null);try{const response=await fetch('/api/oraculum/rc1-selftest',{cache:'no-store'});const data=await response.json();if(!data.report)throw new Error(data.error||'Self-test não retornou relatório.');setReport(data.report as Report);if(!response.ok&&!data.report.passed)setError('A RC1 apresentou uma ou mais divergências. Veja os checks abaixo.');}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao executar self-test.');}finally{setBusy(false);}}
 function downloadEvidence(){if(!report)return;const evidence={evidenceKind:'HOC-RC1-RUNTIME-QA-EVIDENCE/V1',exportedAt:new Date().toISOString(),releaseId:report.releaseId,report,note:'Runtime QA evidence only. Does not replace repository CI, typecheck, production build, physical QA or human promotion approval.'};const blob=new Blob([JSON.stringify(evidence,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`HOC-RC1-RUNTIME-QA-${report.passed?'PASS':'FAIL'}.json`;anchor.click();URL.revokeObjectURL(url);}
 useEffect(()=>{void run();},[]);
 return <main className={styles.shell}><header className={styles.hero}><div><p className={styles.kicker}>HOC V1.0 RC1 · QA HUB</p><h1>Validação da Release Candidate</h1><p>Execute o self-test do runtime e navegue pelos gates que exigem evidência física e de dispositivo. Nenhum painel substitui CI, build ou promoção humana.</p><p><Link href="/oraculum">← voltar ao Oraculum</Link> · <Link href="/oraculum/qa/evidence">Evidence Ledger</Link> · <Link href="/oraculum/qa/readiness">Promotion Readiness</Link> · <Link href="/oraculum/qa/decision">Human Decision</Link> · <Link href="/oraculum/verify">verificar manifesto →</Link></p></div><div className={styles.badge}>{report?.passed?'RC1 SELF-TEST PASS':'RC1 QA'}</div></header>
 <section className={styles.card}><h2>Trilhas de QA</h2><div className={styles.resultGrid}><article className={styles.resultCard}><small>Runtime</small><strong><Link href="/oraculum/qa">Self-test RC1</Link></strong><p>Vetores e protocolos congelados no runtime Node.</p></article><article className={styles.resultCard}><small>Physical</small><strong><Link href="/oraculum/qa/physical">Cubo real</Link></strong><p>STATE resolvido + RITUAL_32 oficial.</p></article><article className={styles.resultCard}><small>Camera / Device</small><strong><Link href="/oraculum/qa/camera">Dispositivo real</Link></strong><p>Câmera, seis faces, confiança e checklist end-to-end.</p></article><article className={styles.resultCard}><small>Evidence</small><strong><Link href="/oraculum/qa/evidence">Release Evidence Ledger</Link></strong><p>Agrega os JSONs e mostra PASS / PENDING / BLOCKED.</p></article><article className={styles.resultCard}><small>Readiness</small><strong><Link href="/oraculum/qa/readiness">RC1 → V1.0</Link></strong><p>Transforma o ledger em blockers, pendências e prontidão para revisão humana.</p></article><article className={styles.resultCard}><small>Decision</small><strong><Link href="/oraculum/qa/decision">Human Decision Record</Link></strong><p>Registra APPROVE / DEFER / REJECT sem executar promoção.</p></article><article className={styles.resultCard}><small>Manifest</small><strong><Link href="/oraculum/verify">Verificador V0.10</Link></strong><p>Recalcula a integridade de um manifesto exportado.</p></article></div></section>
 <section className={styles.card}><h2>Runtime self-test</h2><div className={styles.inlineActions}><button type="button" onClick={run} disabled={busy}>{busy?'Executando…':'Executar novamente'}</button><button type="button" onClick={downloadEvidence} disabled={!report}>Baixar evidência JSON</button></div>{error&&<p className={styles.error}>{error}</p>}{!report&&busy&&<p>Validando protocolos e vetores oficiais…</p>}{report&&<><div className={report.passed?styles.validState:styles.invalidState}>{report.passed?'✓ RC1 runtime íntegro':'✗ RC1 com divergências'} · {report.passedChecks}/{report.totalChecks} checks PASS</div><div className={styles.resultGrid}><article className={styles.resultCard}><small>Release</small><strong>{report.releaseId}</strong></article><article className={styles.resultCard}><small>Self-test</small><strong>{report.version}</strong></article><article className={styles.resultCard}><small>PASS</small><strong>{report.passedChecks}</strong></article><article className={styles.resultCard}><small>FAIL</small><strong>{report.failedChecks}</strong></article></div></>}</section>
 {report&&<section className={styles.card}><h2>Protocolos congelados</h2><div className={styles.resultGrid}>{Object.entries(report.protocols).map(([key,value])=><article className={styles.resultCard} key={key}><small>{key}</small><strong>{value}</strong></article>)}</div></section>}{report&&<section className={styles.card}><h2>Matriz de checks</h2><div className={styles.analysisGrid}>{report.checks.map(check=><article className={styles.analysisCard} key={check.id}><div className={check.passed?styles.validState:styles.invalidState}>{check.passed?'PASS':'FAIL'}</div><h3>{check.id}</h3>{!check.passed&&<pre className={styles.audit}>{JSON.stringify({expected:check.expected,actual:check.actual},null,2)}</pre>}</article>)}</div></section>}
 <section className={styles.card}><h2>O que este hub não prova</h2><p>Um PASS de runtime não substitui CI, build de produção nem QA com cubo físico. Ainda são gates separados: instalação limpa, TypeScript, build Next.js, execução em dispositivo, câmera, cubo físico STATE, RITUAL_32 real e validação cross-device do manifesto.</p></section></main>;
}
